# Generated by Django 5.1.5 on 2025-02-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fee_calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_port_prices', to='Fee_calculator.port')),
                ('station_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_port_prices', to='Fee_calculator.port')),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cuttoff_dare', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_station', models.IntegerField()),
                ('number_of_day', models.IntegerField()),
                ('port_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to='price.portprice')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(choices=[('20ft', '20ft'), ('40ft', '40ft'), ('20ft Fresser', '20ft Fresser'), ('40HC', '40HC')], max_length=255)),
                ('pickup', models.DecimalField(decimal_places=2, max_digits=10)),
                ('port_of_origin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ocean_freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('port_of_discharge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='price.vessel')),
            ],
        ),
    ]
