# Generated by Django 5.1.5 on 2025-04-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portprice',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='container',
            field=models.CharField(blank=True, choices=[('20ft', '20ft'), ('40ft', '40ft'), ('20ft Fresser', '20ft Fresser'), ('40HC', '40HC')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='ocean_freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='pickup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='port_of_discharge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='port_of_origin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
