# Generated by Django 5.1.5 on 2025-06-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_portprice_visible_alter_price_container_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='added_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
