# Generated by Django 5.1.5 on 2025-06-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_price_added_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='ocean_freight_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
