# Generated by Django 4.2.3 on 2025-07-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0004_price_ocean_freight_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='sold_out',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
