# Generated by Django 4.2.3 on 2025-07-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_price_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='solds_out',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
