# Generated by Django 5.1.5 on 2025-02-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_arabic', models.CharField(max_length=255)),
                ('airport_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Atom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CountryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='FeesGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_arabic', models.CharField(max_length=255)),
                ('port_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=4, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('label_en', models.CharField(max_length=1024)),
                ('label', models.CharField(max_length=1024)),
                ('export1', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('spending_fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('support_fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('protection_fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('natural_fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tax_fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('local_fee', models.DecimalField(decimal_places=4, max_digits=10)),
                ('gold', models.DecimalField(decimal_places=4, max_digits=10)),
                ('paper', models.DecimalField(decimal_places=4, max_digits=10)),
                ('brid', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=255)),
                ('unit_en', models.CharField(max_length=255)),
                ('Import_fee', models.DecimalField(decimal_places=4, default=0.01, max_digits=10)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('placeholder_en', models.CharField(blank=True, max_length=255, null=True)),
                ('decision', models.CharField(blank=True, max_length=4024, null=True)),
                ('decision_en', models.CharField(blank=True, max_length=4024, null=True)),
                ('dolar', models.ForeignKey(db_column='dolar_id', on_delete=django.db.models.deletion.CASCADE, to='Fee_calculator.dolar')),
                ('feesGroup', models.ManyToManyField(blank=True, to='Fee_calculator.feesgroup')),
                ('total_taxes', models.ForeignKey(db_column='taxes_id', on_delete=django.db.models.deletion.CASCADE, to='Fee_calculator.taxes')),
            ],
        ),
        migrations.CreateModel(
            name='Export_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=25, null=True)),
                ('decision', models.CharField(blank=True, max_length=4024, null=True)),
                ('Lowest_price', models.CharField(blank=True, max_length=25, null=True)),
                ('highest_price', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.CharField(blank=True, max_length=25, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('fees_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='export_price', to='Fee_calculator.fees')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ar', 'عربي'), ('en', 'english')], default='ar', max_length=2)),
                ('label', models.CharField(max_length=255)),
                ('label_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('ImageURL', models.CharField(max_length=255)),
                ('countries_code', models.CharField(max_length=255)),
                ('countryGroups', models.ManyToManyField(to='Fee_calculator.countrygroup')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('label_en', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('lycra', models.BooleanField(default=False)),
                ('colored_thread', models.BooleanField(default=False)),
                ('Brand', models.BooleanField(default=False)),
                ('tubes', models.BooleanField(default=False)),
                ('countryGroups', models.ManyToManyField(blank=True, to='Fee_calculator.countrygroup')),
                ('fees', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='Fee_calculator.fees')),
                ('origin', models.ManyToManyField(blank=True, to='Fee_calculator.origin')),
            ],
        ),
    ]
