# Generated by Django 5.1.5 on 2025-04-17 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tree_view', '0004_alter_exportfee_options_alter_importfee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Air_Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('loading_address', models.CharField(blank=True, max_length=100, null=True)),
                ('discharge_address', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actual_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('volumetric_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contant_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('massage', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customs_Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(choices=[('استيراد', 'استيراد'), ('تصدير', 'تصدير')], max_length=10)),
                ('transportation_type', models.CharField(choices=[('بري', 'بري'), ('بحري', 'بحري'), ('جوي', 'جوي')], max_length=10)),
                ('goods_weight', models.CharField(blank=True, max_length=926, null=True)),
                ('goods_type', models.CharField(blank=True, max_length=200, null=True)),
                ('package_type', models.CharField(blank=True, max_length=200, null=True)),
                ('number_package', models.CharField(blank=True, max_length=200, null=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('clearance_location', models.CharField(max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('Tab_name', models.CharField(max_length=100)),
                ('Field_type', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('massage', models.CharField(max_length=1500)),
                ('problem', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Communication_method', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Land_Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_weight', models.CharField(blank=True, max_length=926, null=True)),
                ('goods_type', models.CharField(blank=True, max_length=926, null=True)),
                ('goods_description', models.CharField(blank=True, max_length=926, null=True)),
                ('loading_address', models.CharField(blank=True, max_length=926, null=True)),
                ('discharge_address', models.CharField(blank=True, max_length=926, null=True)),
                ('goods_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sea_Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_weight', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('goods_type', models.CharField(blank=True, max_length=900, null=True)),
                ('goods_description', models.CharField(blank=True, max_length=900, null=True)),
                ('movement_type', models.CharField(blank=True, max_length=900, null=True)),
                ('loading_address', models.CharField(blank=True, max_length=255, null=True)),
                ('discharge_address', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=900, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, max_length=150, null=True)),
                ('shipping_service', models.CharField(blank=True, max_length=150, null=True)),
                ('station_origin', models.CharField(blank=True, max_length=150, null=True)),
                ('station_delivery', models.CharField(blank=True, max_length=150, null=True)),
                ('ocean_freight', models.CharField(blank=True, max_length=150, null=True)),
                ('port_of_origin', models.CharField(blank=True, max_length=150, null=True)),
                ('port_of_destination', models.CharField(blank=True, max_length=150, null=True)),
                ('total_price', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_day', models.IntegerField()),
                ('containers_details', models.CharField(blank=True, max_length=150, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('commodity_description', models.TextField(null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_method', models.CharField(blank=True, max_length=255, null=True)),
                ('book_code', models.CharField(max_length=15, null=True)),
                ('commodity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='Good_Air',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_type', models.CharField(blank=True, max_length=926, null=True)),
                ('goods_weight', models.CharField(blank=True, max_length=80, null=True)),
                ('number_package', models.CharField(blank=True, max_length=80, null=True)),
                ('Package_width', models.CharField(blank=True, max_length=80, null=True)),
                ('Package_height', models.CharField(blank=True, max_length=80, null=True)),
                ('Package_length', models.CharField(blank=True, max_length=80, null=True)),
                ('air_freight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_air', to='Sea_Shipping.air_freight')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_type', models.CharField(max_length=255)),
                ('container_number', models.CharField(max_length=255)),
                ('length', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('Width', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sea_shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='Sea_Shipping.sea_shipping')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(max_length=20)),
                ('truck_number', models.CharField(max_length=20)),
                ('land_shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='Sea_Shipping.land_shipping')),
            ],
        ),
    ]
