# Generated by Django 5.1.5 on 2025-02-02 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 3, 8, 58, 26, 986127, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
