# Generated by Django 5.1.5 on 2025-02-02 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_verification_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 3, 9, 2, 58, 799182, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
