# Generated by Django 5.1.5 on 2025-02-17 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_user_verification_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 6, 57, 6, 969762, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
