# Generated by Django 4.2.3 on 2025-07-02 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_verification_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 3, 6, 44, 58, 412498, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
