# Generated by Django 5.1.5 on 2025-02-16 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_fee', models.CharField(max_length=255, null=True)),
                ('export_fee', models.CharField(max_length=255, null=True)),
                ('full_import_fee', models.CharField(max_length=255, null=True)),
                ('full_export_fee', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code', models.CharField(max_length=25, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tariffa/item/')),
                ('unit', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=2, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tariffa/section/')),

            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='AdditionalConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('language', models.CharField(max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_conditions', to='tariffa.item')),
            ],
            options={
                'verbose_name': 'Additional Condition',
                'verbose_name_plural': 'Additional Conditions',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='tariffa.section')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='SubChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, unique=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_chapters', to='tariffa.chapter')),
            ],
            options={
                'verbose_name': 'Sub-Chapter',
                'verbose_name_plural': 'Sub-Chapters',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='sub_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tariffa.subchapter'),
        ),
        migrations.CreateModel(
            name='ChapterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tariffa.chapter')),
            ],
            options={
                'verbose_name': 'Chapter Translation',
                'verbose_name_plural': 'Chapter Translations',
                'unique_together': {('chapter', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tariffa.item')),
            ],
            options={
                'verbose_name': 'Item Translation',
                'verbose_name_plural': 'Item Translations',
                'unique_together': {('item', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tariffa.section')),
            ],
            options={
                'verbose_name': 'Section Translation',
                'verbose_name_plural': 'Section Translations',
                'unique_together': {('section', 'language')},
            },
        ),
        migrations.CreateModel(
            name='SubChapterTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('sub_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tariffa.subchapter')),
            ],
            options={
                'verbose_name': 'Sub-Chapter Translation',
                'verbose_name_plural': 'Sub-Chapter Translations',
                'unique_together': {('sub_chapter', 'language')},
            },
        ),
    ]
