# Generated by Django 5.1.5 on 2025-02-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='test',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='section',
            name='test2',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
