# Generated by Django 5.1.5 on 2025-02-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=926, null=True)),
                ('label_en', models.CharField(max_length=926, null=True)),
                ('is_have_note', models.BooleanField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HsCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('hs_code', models.CharField(max_length=50, unique=True)),
                ('image', models.FileField(null=True, upload_to='media/items/images')),
                ('label', models.CharField(max_length=926, null=True)),
                ('label_en', models.CharField(max_length=926, null=True)),
                ('review', models.CharField(blank=True, max_length=512, null=True)),
                ('review_en', models.CharField(blank=True, max_length=512, null=True)),
                ('review_value', models.CharField(blank=True, max_length=2, null=True)),
                ('import_fee', models.CharField(max_length=926, null=True)),
                # ('export_fee', models.CharField(max_length=926, null=True)),
                ('services_allowance', models.CharField(max_length=926, null=True)),
                ('unit', models.CharField(choices=[('number', 'Number'), ('weight', 'Weight')], default='number', max_length=10)),
            ],
            options={
                'ordering': ['hs_code', 'id_parent_3'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('number', models.IntegerField(default=77)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=512, null=True)),
                ('label_en', models.CharField(max_length=512, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('image', models.FileField(null=True, upload_to='media/fees/images')),
                ('start', models.CharField(max_length=8, null=True)),
                ('end', models.CharField(max_length=8, null=True)),
                ('is_have_note', models.BooleanField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance', models.TextField(blank=True, null=True)),
                ('finance_en', models.TextField(blank=True, null=True)),
                ('id_finance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financefees', to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='ExportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('export', models.CharField(blank=True, max_length=512, null=True)),
                ('restriction_export', models.CharField(blank=True, max_length=1024, null=True)),
                ('export_en', models.CharField(blank=True, max_length=512, null=True)),
                ('restriction_export_en', models.CharField(blank=True, max_length=1024, null=True)),
                ('id_exportfee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exportfees', to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial_Description',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('second_description', models.TextField(blank=True, null=True)),
                ('id_desc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='Image_Description',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('image', models.FileField(null=True, upload_to='media/fees/images_desc')),
                ('id_desc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='ImportFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('restriction_import', models.TextField(blank=True, max_length=512, null=True)),
                ('document_import', models.CharField(blank=True, max_length=512, null=True)),
                ('restriction_import_en', models.TextField(blank=True, max_length=512, null=True)),
                ('document_import_en', models.CharField(blank=True, max_length=512, null=True)),
                ('id_importfee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importfees', to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='Notes_chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('note_a', models.TextField(blank=True, null=True)),
                ('note_b', models.TextField(blank=True, null=True)),
                ('note_c', models.TextField(blank=True, null=True)),
                ('note_d', models.TextField(blank=True, null=True)),
                ('note_e', models.TextField(blank=True, null=True)),
                ('note_num', models.CharField(max_length=35, null=True)),
                ('note_a_en', models.TextField(blank=True, null=True)),
                ('note_b_en', models.TextField(blank=True, null=True)),
                ('note_c_en', models.TextField(blank=True, null=True)),
                ('note_d_en', models.TextField(blank=True, null=True)),
                ('note_e_en', models.TextField(blank=True, null=True)),
                ('note_num_en', models.CharField(max_length=35, null=True)),
                ('id_chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Notes_fee',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('note_a', models.TextField(blank=True, null=True)),
                ('note_b', models.TextField(blank=True, null=True)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('name_a', models.TextField(blank=True, null=True)),
                ('name_b', models.TextField(blank=True, null=True)),
                ('name_addition', models.TextField(blank=True, null=True)),
                ('note_a_en', models.TextField(blank=True, null=True)),
                ('note_b_en', models.TextField(blank=True, null=True)),
                ('additional_note_en', models.TextField(blank=True, null=True)),
                ('name_a_en', models.TextField(blank=True, null=True)),
                ('name_b_en', models.TextField(blank=True, null=True)),
                ('name_addition_en', models.TextField(blank=True, null=True)),
                ('id_fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='Notes_section',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('note_a', models.TextField(blank=True, null=True)),
                ('note_b', models.TextField(blank=True, null=True)),
                ('note_c', models.TextField(blank=True, null=True)),
                ('note_num', models.CharField(max_length=35, null=True)),
                ('note_a_en', models.TextField(blank=True, null=True)),
                ('note_b_en', models.TextField(blank=True, null=True)),
                ('note_c_en', models.TextField(blank=True, null=True)),
                ('note_num_en', models.CharField(max_length=35, null=True)),
                ('id_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.section')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='id_parent_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.section'),
        ),
        migrations.CreateModel(
            name='Stone_Farming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ston_import', models.TextField(blank=True, null=True)),
                ('ston_import_notes', models.TextField(blank=True, null=True)),
                ('ston_export', models.TextField(blank=True, null=True)),
                ('ston_export_notes', models.TextField(blank=True, null=True)),
                ('ston_import_en', models.TextField(blank=True, null=True)),
                ('ston_import_notes_en', models.TextField(blank=True, null=True)),
                ('ston_export_en', models.TextField(blank=True, null=True)),
                ('ston_export_notes_en', models.TextField(blank=True, null=True)),
                ('id_stone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stonefarms', to='tree_view.hscode')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Chapter',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=926, null=True)),
                ('label_en', models.CharField(max_length=926, null=True)),
                ('review', models.CharField(blank=True, max_length=512, null=True)),
                ('review_en', models.CharField(blank=True, max_length=512, null=True)),
                ('review_value', models.CharField(blank=True, max_length=2, null=True)),
                ('id_parent_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Notes_subchapter',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('note_a', models.TextField(blank=True, null=True)),
                ('additional_note', models.TextField(blank=True, null=True)),
                ('name_a', models.TextField(blank=True, null=True)),
                ('name_addition', models.TextField(blank=True, null=True)),
                ('note_a_en', models.TextField(blank=True, null=True)),
                ('additional_note_en', models.TextField(blank=True, null=True)),
                ('name_a_en', models.TextField(blank=True, null=True)),
                ('name_addition_en', models.TextField(blank=True, null=True)),
                ('id_subchapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.sub_chapter')),
            ],
        ),
        migrations.AddField(
            model_name='hscode',
            name='id_parent_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.sub_chapter'),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=926, null=True)),
                ('label_en', models.CharField(max_length=926, null=True)),
                ('review', models.CharField(blank=True, default='Nill', max_length=512)),
                ('review_en', models.CharField(blank=True, default='Nill', max_length=512)),
                ('review_value', models.CharField(blank=True, default='Nill', max_length=2)),
                ('id_parent_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.sub_chapter')),
            ],
        ),
    ]
