# Generated by Django 5.1.5 on 2025-03-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_view', '0001_initial'),
    ]

    operations = [
 
     
        migrations.AddField(
            model_name='hscode',
            name='export_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
      
    ]
