# Generated by Django 5.1.5 on 2025-03-18 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_view', '0002_alter_exportfee_options_alter_importfee_options_and_more'),
    ]

    operations = [
migrations.AddField(
            model_name='hscode',
            name='test',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
