# Generated by Django 5.1.5 on 2025-04-17 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_view', '0003_alter_exportfee_options_alter_importfee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportfee',
            options={'verbose_name_plural': 'ExportAll'},
        ),
        migrations.AlterModelOptions(
            name='importfee',
            options={'verbose_name_plural': 'ImportAll'},
        ),
        migrations.RenameField(
            model_name='exportfee',
            old_name='active',
            new_name='export_allowed',
        ),
        migrations.RenameField(
            model_name='importfee',
            old_name='active',
            new_name='import_allowed',
        ),
        migrations.RemoveField(
            model_name='hscode',
            name='services_allowance',
        ),
        migrations.AddField(
            model_name='hscode',
            name='checking',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='hscode',
            name='exp_ser_Fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hscode',
            name='new',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='hscode',
            name='ser_all',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exportfee',
            name='export',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='hs_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='id_parent_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_view.sub_chapter'),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/items/image'),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='import_fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
