# Generated by Django 4.2.3 on 2025-06-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_view', '0004_alter_exportfee_options_alter_importfee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscode',
            name='type',
            field=models.CharField(blank=True, max_length=926, null=True),
        ),
    ]
