# Generated by Django 4.2.3 on 2025-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_view', '0005_hscode_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hscode',
            name='exp_ser_Fe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price Export'),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='export_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Clearance Fee Export'),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='hs_code',
            field=models.CharField(max_length=50, verbose_name='Band'),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='import_fee',
            field=models.FloatField(blank=True, null=True, verbose_name='Price Import'),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='label',
            field=models.CharField(max_length=926, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hscode',
            name='ser_all',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Clearance Fee'),
        ),
    ]
