# Generated by Django 4.2.3 on 2025-07-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscode',
            name='full_import_fee2',
            field=models.CharField(blank=True, max_length=926, null=True, verbose_name='Price Full'),
        ),
    ]
