# Generated by Django 4.2.3 on 2025-07-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_hscode_full_import_fee2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hscode',
            old_name='full_import_fee2',
            new_name='full_import_fee',
        ),
    ]
