# Generated by Django 3.2 on 2024-10-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(blank=True, max_length=255, null=True)),
                ('container_type', models.CharField(blank=True, choices=[('20 FT', '20 FT'), ('40 FT', '40 FT'), ('40 HC', '40 HC'), ('20 HC', '20 HC')], max_length=255, null=True)),
                ('type_of_goods', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_packages_in_container', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='media/track')),
            ],
        ),
        migrations.CreateModel(
            name='StationNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_station', models.CharField(blank=True, max_length=255, null=True)),
                ('image_station', models.FileField(upload_to='media/track')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('station_type', models.CharField(choices=[('ترانزيت', 'ترانزيت'), ('رئيسي', 'رئيسي')], max_length=255)),
                ('transportation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('gatein_date', models.DateField(blank=True, null=True)),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.containerdetails')),
                ('station_nature', models.ManyToManyField(to='tracking.StationNature')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('images', models.ManyToManyField(blank=True, to='tracking.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('assign_stations', models.BooleanField()),
                ('number_of_container', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_packages', models.CharField(blank=True, max_length=255, null=True)),
                ('Total_gross_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('General_type_goods', models.CharField(blank=True, max_length=512, null=True)),
                ('shipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.shipmenttype')),
            ],
        ),
        migrations.AddField(
            model_name='containerdetails',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.shipment'),
        ),
    ]
