# Generated by Django 4.2.3 on 2025-07-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_address', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('item_description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
            ],
        ),
    ]
